version: "3.9"

services:
  app:
  image : ghcr.io/develmts/neptunereport:latest
    working_dir: /usr/src/app
    volumes:
      - neptune-data:/usr/src/app
    environment:
      GIT_REPO_URL: https://github.com/develmts/neptunereport.git
      GIT_BRANCH: "main"    
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - services  
volumes:
  myapp-volume:

networks:
  services:
    external: true